### ISSUE TITLE
Card Component does not have alt prop for image

### ISSUE THREAD

**Issue by is4g4i** [markteekman/accessible-astro-components#33] opened 2022-11-21 17:19 UTC
The alt prop for the image is "" and does not appear at the astro props.

const { 
  url = '#', 
  img = 'https://fakeimg.pl/640x360', 
  title = 'Default title', 
  footer = 'Your name'
} = Astro.props

**Comment by markteekman** [comment] 2022-11-21 19:19
Hey @is4g4i! Thanks for submitting the issue. The `<img>` tag of the Card component has an empty `alt=""` attribute because in most cases, it will be decorative. That's how it's intended for this particular component. Do you have a use case where you need the image to be informative?

**Comment by is4g4i** [comment] 2022-11-21 19:31
If it's intended, maybe an optional prop can be the solution.
The alt in images is suppossed to be always present for those folks with visual disabilities.

**Comment by markteekman** [comment] 2022-11-22 08:42
I agree with you @is4g4i! If it is intended to be informative then there should be an option. In must cases though, the heading and the paragraph of the Card will convey the message to sighted and visually impaired users. That's how this Card was designed. The image should only describe something that isn't already told by the heading and the paragraph and could lead to repeating the same information if not used correctly. The Card design is inspired by [Heydon Pickerings](https://inclusive-components.design/cards/) view of how to build a Card component, in which he uses an empty `alt=""` tag. He does mention the use of a descriptive image, but this means the structure becomes incorrect (content before a heading), which can be solved using the Flexbox order property. With that it should work, but it will look a little funny to sighted users as the visual focus is a little weird this way.

Taking al this into account it both has advantages and disadvantages. Since most use cases (9 out of 10) won't be using the alt tag it would be better to keep it this way rather then to switch the order (and thus the visual focus) using Flexbox. It would however be a great idea to design another Card that ís descriptive in it's nature, intended for the other use case 🙂

**Comment by markteekman** [comment] 2023-01-10 14:51
Closing this for now and keeping an alternative Card component on the roadmap.

**Closed by markteekman** 2023-01-10 14:51 UTC
Labels: good first issue, more info required

**Comment by jasonday** [comment] 2025-03-11 19:25
@markteekman - current thinking has changed a bit on this, and the general conclusion is that almost no images are decorative. If it provides meaning to a sighted user, then it should for assistive technology users. For example, sighted users skim the page visually and look at the card images - they provide context for us beyond just decoration. Due to that, I also think an alt attribute would be useful here as @is4g4i stated.

**Comment by markteekman** [comment] 2025-03-13 18:33
@jasonday I definitely understand what your saying when you put it like that. It's not something that I see getting mentioned in audits we had done for websites at the company I work at though. I'll consult our accessibility partner about it! Do you have any reference or resources providing context for this?

**Comment by jasonday** [comment] 2025-03-15 00:47
@is4g4i - I created a copy of the Card component to use the <Image/> helper, and pull in alt text:

Code:
[gist.github.com/jasonday/7239eb243efd70cbc65448b0f4a5ed1c](https://gist.github.com/jasonday/7239eb243efd70cbc65448b0f4a5ed1c)
